import assert from 'node:assert/strict';
import {createQaSocialServer} from './qa-social-server.js';
const values=new Map(),now=1000000;
const storage={async get(k){return values.get(k)?.value??null},async set(k,value,opts){values.set(k,{value,ttl:opts.ttl})},async delete(k){values.delete(k)}};
let n=0;const server=createQaSocialServer(storage,{now:()=>now,uuid:()=>('f0000000-0000-4000-8000-'+String(++n).padStart(12,'0'))});
const call=(path,method='GET',body={},token='',query={})=>server.route({path,method,body,query,headers:token?{authorization:'Bearer '+token}:{}});
const enroll=async(clientKey,name)=>{const x=await call('register','POST',{clientKey,name,handle:name.toLowerCase()});assert.equal(x.status,200);return x.body};
const a=await enroll('client-key-abcdefghijklmnopqrstuv001','Prueba');
const b=await enroll('client-key-abcdefghijklmnopqrstuv002','Martina');
const c=await enroll('client-key-abcdefghijklmnopqrstuv003','Hebert');
const tokA=a.token,tokB=b.token,tokC=c.token;
assert.notEqual(a.user.id,b.user.id);
assert.equal((await call('me','GET',{},tokA)).body.user.id,a.user.id);
assert.equal((await call('me','GET',{},'fake')).status,401,'reject forged bearer');
const state=(peer,x,seq)=>({peerId:peer,x,y:110,seq,color:'navy',dir:'S',moving:true});
assert.equal((await call('lobby/state','POST',state('peer-prueba-01',100,1),tokA)).status,200);
assert.equal((await call('lobby/state','POST',state('peer-martina-01',150,2),tokB)).status,200);
const roster=(await call('lobby','GET',{},tokA)).body.players;
assert.equal(roster.length,2,'both devices visible to one another');
assert(roster.some(x=>x.userId===a.user.id)&&roster.some(x=>x.userId===b.user.id));
assert.equal((await call('search','GET',{},tokA,{q:'martina'})).body.users[0].id,b.user.id);
assert.equal((await call('friends','POST',{userId:b.user.id},tokA)).status,200);
assert.equal((await call('me','GET',{},tokB)).body.requests.incoming[0].id,a.user.id);
assert.equal((await call('friends/accept','POST',{userId:a.user.id},tokB)).status,200);
assert.equal((await call('me','GET',{},tokA)).body.friends[0].id,b.user.id);
const room=(await call('rooms','POST',{mode:'coop',invitees:[b.user.id],peerId:'peer-prueba-01'},tokA)).body.room;
assert.equal(room.members.length,1);assert.equal(room.allAccepted,false);
const invite=(await call('me','GET',{},tokB)).body.invites[0];assert.equal(invite.roomId,room.id);
assert.equal((await call('rooms/join','POST',{roomId:room.id,peerId:'peer-martina-01'},tokB)).status,200);
const joined=(await call('rooms/'+room.id+'/messages','GET',{},tokA)).body.room;
assert.equal(joined.members.length,2);assert.equal(joined.allAccepted,true,'all accepted');
assert.equal((await call('rooms/'+room.id+'/messages','POST',{message:{type:'chat',text:'listo'}},tokA)).status,200);
assert.equal((await call('rooms/'+room.id+'/messages','GET',{},tokB,{after:0})).body.messages.length,1);
assert.equal((await call('rooms/'+room.id+'/messages','GET',{},tokC)).status,403,'outsider cannot read private party');
const text=await call('lobby/chat','POST',{text:'Hola'},tokA);
assert.equal(text.status,200);
assert.equal((await call('lobby','GET',{},tokB,{after:0})).body.messages.at(-1).text,'Hola');
const sig=await server.signalRoute({method:'POST',body:{signal:{type:'offer',fromUserId:a.user.id,fromPeerId:'peer-prueba-01',toPeerId:'peer-martina-01',description:{type:'offer',sdp:'qa-test'}}},headers:{authorization:'Bearer '+tokA}});
assert.equal(sig.status,200);
assert.equal((await server.signalRoute({method:'GET',query:{signal:'offer',toPeer:'peer-martina-01',fromPeer:'peer-prueba-01'},headers:{authorization:'Bearer '+tokB}})).body.signal.description.sdp,'qa-test');
assert.equal((await call('lobby/leave','POST',{},tokB)).status,200);
assert.equal((await call('lobby','GET',{},tokA)).body.players.length,1);
const badInvite=await call('rooms/'+room.id+'/invite/decline','POST',{},tokC);
assert.equal(badInvite.status,403,'non-invited users cannot decline another group invitation');
const xInvite=await call('rooms/'+room.id+'/invite','POST',{userId:c.user.id},tokA);
assert.equal(xInvite.status,200);
assert.equal((await call('me','GET',{},tokC)).body.invites.length,1);
assert.equal((await call('rooms/'+room.id+'/invite/decline','POST',{},tokC)).status,200,'invited user may decline');
assert.equal((await call('me','GET',{},tokC)).body.invites.length,0,'declined invite must disappear');
console.log('ATRIA QA social two-user presence, friend, invitations, coop, chat, security and signal simulation PASS');

const staleA=await call('lobby/state','POST',{peerId:'peer-prueba-01',x:500,y:200,seq:8},tokA);
assert.equal(staleA.status,200);
const delayedA=await call('lobby/state','POST',{peerId:'peer-prueba-01',x:70,y:100,seq:7},tokA);
assert.equal(delayedA.body.stale,true,'older movement snapshots must not rewind the player');
assert.equal((await call('lobby','GET',{},tokA)).body.players.find(x=>x.userId===a.user.id)?.x,500,'stale packet cannot teleport avatar backwards');
console.log('QA server prevents out-of-order movement rewind');
