import assert from'node:assert/strict';import{roomReducer}from'./room-state.js';
let s={phase:'lobby',players:[]};for(const id of ['a','b','c','d'])s=roomReducer(s,{type:'JOIN',id});assert.equal(s.players.length,4);
s=roomReducer(s,{type:'READY'});assert.equal(s.phase,'ready');s=roomReducer(s,{type:'START',token:'g1'});assert.equal(s.phase,'starting');
for(const id of ['a','b','c'])s=roomReducer(s,{type:'ACK_START',id,token:'g1'});assert.equal(s.phase,'starting');s=roomReducer(s,{type:'ACK_START',id:'d',token:'g1'});assert.equal(s.phase,'active');
let t={phase:'starting',players:['a','b'],startAcks:['a'],startToken:'stale'};t=roomReducer(t,{type:'START_TIMEOUT'});assert.equal(t.phase,'ready');assert.deepEqual(t.startAcks,[]);assert.equal(t.startToken,null);
let bad={phase:'starting',players:['a','b'],startAcks:[],startToken:'new'};bad=roomReducer(bad,{type:'ACK_START',id:'a',token:'stale'});assert.deepEqual(bad.startAcks,[]);
let active={phase:'active',players:['a','b'],startAcks:['a','b']};active=roomReducer(active,{type:'LEAVE',id:'b'});assert.equal(active.phase,'ended');
let restart={phase:'ready',players:['a','b'],startAcks:['a','b'],startToken:'old'};restart=roomReducer(restart,{type:'START',token:'new'});assert.deepEqual(restart.startAcks,[],'new start must discard stale ACKs');restart=roomReducer(restart,{type:'ACK_START',id:'a',token:'new'});assert.equal(restart.phase,'starting');
let drop={phase:'starting',players:['a','b'],startAcks:['a'],startToken:'x'};drop=roomReducer(drop,{type:'LEAVE',id:'b'});assert.equal(drop.phase,'ready');assert.equal(drop.startToken,null);assert.deepEqual(drop.startAcks,[]);
console.log('room state OK');
