import assert from'node:assert/strict';import fs from'node:fs';import{apply487}from'./apply-487.js';
const src=fs.readFileSync('vendor/atria-4.8.6/index.html','utf8'),out=apply487(src);
assert.match(out,/Sin alteraciones significativas para esta patología\./);
assert.match(src,/task7\.js\?v=483/,'golden master must retain legacy task7 fallback loader');
assert.doesNotMatch(out,/task7\.js\?v=483/,'4.8.7 artifact must not load superseded task7 study fallback');
assert.match(src,/task8\.js\?v=482/,'golden master must retain legacy task8 loader');
assert.match(src,/task12\.js\?v=485/,'golden master must retain legacy task12 loader');
assert.doesNotMatch(out,/task8\.js\?v=482/,'4.8.7 artifact must not load legacy task8 DOM poller');
assert.doesNotMatch(out,/task12\.js\?v=485/,'4.8.7 artifact must not load legacy task12 DOM poller');
assert.match(out,/universalFallback:true/);
assert.match(out,/id:'universal_'/,'arbitrary named studies must remain orderable');
assert.doesNotMatch(out,/No pude traducir esa orden/,'study commands must not fall into legacy unrecognized-order response');
assert.equal((out.match(/\*60000/g)||[]).length>=2,true,'study turnaround must use 1 real minute per game hour');
assert.match(out,/csCoop\.dc\.bufferedAmount\|\|0\)>65536/);
assert.equal(out.includes('s.delay*1000'),false,'legacy seconds-scale study timing must be gone');
assert.equal(src.includes('universalFallback:true'),false,'golden master must remain immutable');
assert.doesNotMatch(out,/Radio de voz pendiente/,'candidate must not intentionally disable existing WebRTC voice transport');
assert.match(src,/Radio de voz pendiente/,'golden master remains unchanged while candidate removes the disable gate');
assert.match(out,/atria-boot-paint-guard/,'first paint must be guarded before legacy HUD can flash');
assert.match(out,/classList\.add\('atriaBootReady'\)/,'boot guard must release only after splash creation');
assert.doesNotMatch(out,/Reconectando tu perfil/,'automatic social bootstrap must not expose legacy re-registration failure state');
assert.match(out,/window\.nsLobbyRtcPulse=function/,'RTC must be scheduled by the primary lobby lifecycle');
assert.doesNotMatch(out,/setTimeout\(discovery,250\);requestAnimationFrame\(animate\)/,'duplicate permanent RTC RAF must be removed');
assert.match(out,/\+2500<t/,'social refresh must be bounded in the lobby scheduler');
assert.doesNotMatch(out,/Activa una vez tu perfil social/,'People must never require manual social activation');
assert.doesNotMatch(out,/>Activar<\/button>/,'manual social activation control must be removed');
assert.match(out,/Conectando tu perfil automáticamente/,'People should represent automatic presence bootstrap');
assert.match(out,/ensureSession:async\(\)=>\{const data=await acquireSession\(\);await refresh\(\);return data\.user\}/,'social module must expose one idempotent session owner');
assert.match(out,/await nsSocial\.ensureSession\(\)/,'lobby bootstrap must use the shared session owner');
assert.doesNotMatch(out,/nsSocial\?\.register\?\.\(\)\.then/,'People must not race a second registration caller');
assert.equal((out.match(/window\.nsLobbyRtcPulse=function/g)||[]).length,1,'integrated artifact must have exactly one RTC pulse owner');
assert.equal((out.match(/ensureSession:async/g)||[]).length,1,'integrated artifact must have exactly one exported social session owner');
assert.match(out,/lastRtcSend>=220/,'RTC state sends must be throttled');
assert.match(out,/lastDiscovery>=2500/,'RTC discovery must be bounded');
assert.match(out,/bufferedAmount\|\|0\)>65536/,'shared-mode data channel must apply backpressure');
assert.match(out,/function csRemoteVisual\(/,'guard renderer must interpolate remote network snapshots');
assert.match(out,/\(now-p\.at\)\/220/,'guard interpolation must bridge the legacy 220 ms network cadence');
const remoteDraw=out.match(/function csDrawRemote\(\)\{[\s\S]*?\n\}/)?.[0]||'';
assert.match(remoteDraw,/const p=csRemoteVisual\(r\)/,'guard renderer must sample the interpolated remote pose');
assert.doesNotMatch(remoteDraw,/actor=\{x:r\.x\|\|0,y:r\.y\|\|0/,'guard renderer must not draw raw remote packet coordinates');
assert.doesNotMatch(out,/sesión social vencida/i,'integrated artifact must not expose expired-social-session UX');
assert.match(out,/window\.nsLobbyRtcStop=function/,'lobby RTC must expose deterministic teardown');
assert.match(out,/net\.peers\.clear\(\);net\.roster\.clear\(\);net\.remotes\.clear\(\)/,'RTC teardown must release peer and interpolation state');
assert.match(out,/state\.active=false;window\.nsLobbyRtcStop\?\.\(\)/,'leaving lobby must invoke RTC teardown');
console.log('4.8.7 source integration OK');

assert.doesNotMatch(out,/html\+=\\\\`/,'integrated inline JS must not contain escaped template delimiters');
assert.doesNotMatch(out,/nsEnterLobbySafe/,'timeout watchdog must not replace deterministic lobby initialization');
assert.match(out,/window\.nsLobby\.enter=enter/,'integrated artifact must export lobby enter');
