import {STUDY_TAT_MINUTES} from '../clinical/study-registry.js';
import {CASE_STUDY_CORRELATIONS,CASE_INCIDENTAL_FINDINGS,csCaseStudyFallback} from '../clinical/contextual-study-results.js';
import {roomTransportReady} from '../social/party-transport.js';
import {csVoiceWord,csVoiceCleanSpeech,csMergeSpeech,csVoiceNovelText} from '../voice/transcript-normalizer.js';
import {csVoiceStageRevisions,csVoiceCommitRevisions} from '../voice/revision-buffer.js';
import {csAnamnesisClassify,csAnamnesisFact} from '../clinical/anamnesis-intents.js';
const replaceOnce=(s,from,to,label)=>{const i=s.indexOf(from);if(i<0)throw new Error('integration anchor missing: '+label);if(s.indexOf(from,i+from.length)>=0)throw new Error('integration anchor ambiguous: '+label);return s.slice(0,i)+to+s.slice(i+from.length)};
export function apply487(html){
 let s=html;
 // 4.8.7 replaces the legacy external study-repair pollers with source-level study resolution.
 s=replaceOnce(s,'<script src="/task7.js?v=483"></script>','<!-- legacy study fallback 7 retired in 4.8.7 -->','retire-task7-study-fallback');
 s=replaceOnce(s,'<script src="/task8.js?v=482"></script>','<!-- legacy study poller 8 retired in 4.8.7 -->','retire-task8-study-poller');
 s=replaceOnce(s,'<script src="/task12.js?v=485"></script>','<!-- legacy study poller 12 retired in 4.8.7 -->','retire-task12-study-poller');
 // task13 captures the same clinical PTT gesture before task5 group voice can receive it. Task5 owns mic permission + group peers in 4.8.7.
 s=replaceOnce(s,'<script src="/task13.js?v=486"></script>','<!-- conflicting legacy PTT primer 13 retired in 4.8.7; task5 owns group voice -->','retire-task13-ptt-primer');
 // Prevent the legacy HUD/map from painting before the branded splash exists.
 const bootStyle=`<style id="atria-boot-paint-guard">html:not(.atriaBootReady) body>*{visibility:hidden!important}html:not(.atriaBootReady) body{background:#07121d!important}</style>`;
 s=replaceOnce(s,'</head>',bootStyle+"<style id=\"atria-chat-bottom-anchor\">\n/* Keep the ward transcript immediately above the composer even when the dock expands. */\nbody:not(.keyboardOpen) #chatDock:not(.nsLobbyChat) .chatRecent{position:absolute!important;top:auto!important;bottom:calc(var(--cs-console-input-h,46px) + 3px)!important;height:auto!important;max-height:112px!important}\nbody:not(.keyboardOpen) #chatDock.historyExpanded:not(.nsLobbyChat) .chatRecent{top:auto!important;bottom:calc(var(--cs-console-input-h,46px) + 3px)!important;height:min(42dvh,320px)!important;max-height:min(42dvh,320px)!important;pointer-events:auto!important}\n</style>"+'</head>','first-paint-guard');
 s=replaceOnce(s,`showSplash();renderSelector();brandHud();`,`showSplash();document.documentElement.classList.add('atriaBootReady');renderSelector();brandHud();`,'splash-first-paint-release');
 s=replaceOnce(s,` function showSplash(){const m=document.createElement('section');m.id='nsSplash';m.className='show';m.setAttribute('aria-label','Bienvenido a ATRIA');m.innerHTML='<div class="nsSplashInner">'+logo()+'<p class="nsEyebrow">GUARDIAS QUE ENSEÑAN</p>'+heroHTML()+'<h1>La noche empieza acá.</h1><p>Un hospital vivo. Decisiones clínicas. Tu próximo desafío.</p><button id="nsEnter" class="nsPrimary">'+(csProfile?'Continuar como '+csEscape(csProfile.name):'Crear mi personaje')+' →</button><small>Aprendiz · Solitario · Cooperativo · Competitivo</small></div>';document.body.appendChild(m);m.querySelector('button').onclick=()=>{splashOpen=false;m.classList.remove('show');if(!csProfile)csOpenProfile(true);else if(window.nsLobby?.enter)window.nsLobby.enter();else renderSelector();csHospitalAudio.unlock();};}`,` function showSplash(){const m=document.createElement('section');m.id='nsSplash';m.className='show';m.setAttribute('aria-label','Bienvenido a ATRIA');m.innerHTML='<div class="nsSplashInner">'+logo()+'<p class="nsEyebrow">GUARDIAS QUE ENSEÑAN</p>'+heroHTML()+'<h1>La noche empieza acá.</h1><p>Un hospital vivo. Decisiones clínicas. Tu próximo desafío.</p><button id="nsEnter" class="nsPrimary">'+(csProfile?'Continuar como '+csEscape(csProfile.name):'Crear mi personaje')+' →</button><small>Aprendiz · Solitario · Cooperativo · Competitivo</small></div>';document.body.appendChild(m);m.querySelector('button').onclick=()=>{splashOpen=false;m.classList.remove('show');if(!csProfile)csOpenProfile(true);else if(window.nsLobby?.enter)window.nsLobby.enter();else renderSelector();csHospitalAudio.unlock();};}`,'preserve-direct-splash-lobby-handoff');
 // Pending study timing is driven by performance.now() and updated by updateOrders().
 // Display the remaining game-hours whenever the Studies panel is rendered; collection has no readyAt yet.
 s=replaceOnce(s,"let st=o.status==='done'?'resultado':o.status==='collecting'?'extracción':o.status==='pending'?'pendiente':'solicitado',cl=","let st=o.status==='done'?'resultado':o.status==='collecting'?'extracción':o.status==='pending'?(o.readyAt?csStudyTimeLabel(o.readyAt):'pendiente de extracción'):'solicitado',cl=",'studies-pending-remaining-game-hours');
 // Results are private to the Studies tab; chart/history only exposes availability.
 s=replaceOnce(s,"const res=[...sim.orders.entries()].filter(([id,o])=>o.status==='done').map(([id,o])=>`<b>${esc(o.label)}</b><br>${esc(o.result)}`).join('<br><br>')||'<span class=\"muted\">Sin resultados objetivos disponibles.</span>';return `<div class=\"section\"><b>Motivo</b>${esc(C.chief)}</div><div class=\"section\"><b>Anamnesis adquirida</b>${hist}</div><div class=\"section\"><b>Signos vitales</b>${vit}</div><div class=\"section\"><b>Examen físico</b>${ex}</div><div class=\"section\"><b>Estudios realizados</b>${res}</div>`","const ready=[...sim.orders.values()].filter(o=>o.status==='done').length,res=ready?`<span class=\"muted\">${ready} resultado${ready===1?'':'s'} disponible${ready===1?'':'s'}. Consultá la pestaña Estudios para ver el contenido.</span>`:'<span class=\"muted\">Sin resultados objetivos disponibles.</span>';return `<div class=\"section\"><b>Motivo</b>${esc(C.chief)}</div><div class=\"section\"><b>Anamnesis adquirida</b>${hist}</div><div class=\"section\"><b>Signos vitales</b>${vit}</div><div class=\"section\"><b>Examen físico</b>${ex}</div><div class=\"section\"><b>Estudios realizados</b>${res}</div>`",'study-results-private-to-studies-tab');
 const oldFind=`function findStudy(text){const n=norm(text);let best=null,score=0;for(const s of C.studies)for(const a of [s.label,...s.aliases]){const na=norm(a);if(n.includes(na)&&na.length>score){best=s;score=na.length}}return best}`;
 const newFind=`const csStudyTiming={"hepatograma":70,"hemograma":35,"renal":45,"eco":75,"paracentesis":45,"lipasa":60,"gasometria":10,"tc":120,"inflamatorio":65,"stool":150,"colonoscopia":240,"enterorm":240,"b12":180,"hda_lab":60,"grupo":50,"eda":120,"iron":90,"fobt":45,"staging":180,"cea":120,"pbe_paracentesis":40,"pbe_culture":1440,"pbe_renal":45,"pbe_cbc":35,"peri_cbc":45,"peri_gas":20,"peri_rx":45,"peri_ct":110,"peri_fluid":70,"ter_cbc":55,"ter_ct":120,"ter_culture":1440,"app_cbc":45,"app_urine":35,"app_us":75,"app_ct":110,"chole_cbc":35,"chole_liver":65,"chole_us":75,"ileo_lab":55,"ileo_gas":15,"ileo_xray":40,"ileo_ct":105,"mesi_lab":70,"mesi_gas":15,"mesi_cta":95,"mesi_angio":135,"cholang_cbc":50,"cholang_liver":70,"cholang_us":85,"cholang_ercp":150};
function csStudyDurationMs(s){const chosen=csStudyTiming[String(s?.id||'')],fallback=Number(s?.gameHours??s?.delayHours??s?.delay??1)*60,minutes=Number.isFinite(chosen)?chosen:(Number.isFinite(fallback)&&fallback>0?fallback:60);return Math.max(1,minutes)*1000}
function csStudyTimeLabel(readyAt,now=performance.now()){const remaining=Math.max(1,Math.ceil((readyAt-now)/1000)),hours=Math.floor(remaining/60),minutes=remaining%60;return 'faltan '+(hours?(hours+' h'+(minutes?' '+minutes+' min':'')):(remaining+' min'))+' de juego'}
function csNormalStudyResult(st){const label=String(st?.label||'Estudio'),n=norm(label);if(/cultivo|microbiolog|clostridium|materia fecal|sangre oculta/.test(n))return label+': sin evidencia de patógenos, toxinas ni sangrado oculto significativo.';if(st?.id==='grupo')return label+': tipificación y pruebas de compatibilidad sin incidencias.';if(st?.type==='imaging')return label+': sin hallazgos patológicos agudos ni alteraciones significativas.';if(st?.type==='procedure')return label+': sin hallazgos patológicos relevantes.';return label+': Sin alteraciones significativas; parámetros dentro de límites de referencia.'}
const CASE_STUDY_CORRELATIONS={"CIRR-001":{"pbe_cbc":"hemograma","chole_cbc":"hemograma","chole_liver":"hepatograma","pbe_renal":"renal"},"PANC-001":{"app_cbc":"hemograma","pbe_cbc":"hemograma","chole_cbc":"hemograma","renal":"hemograma","peri_gas":"gasometria","ileo_gas":"gasometria","mesi_gas":"gasometria"},"CROHN-001":{"hemograma":"inflamatorio","pbe_cbc":"inflamatorio","chole_cbc":"inflamatorio","app_cbc":"inflamatorio"},"HDA-001":{"hemograma":"hda_lab","pbe_cbc":"hda_lab","renal":"hda_lab"},"COLON-001":{"hemograma":"iron","pbe_cbc":"iron","chole_cbc":"iron"},"PERI-PBE-001":{"hemograma":"pbe_cbc","chole_cbc":"pbe_cbc","renal":"pbe_renal","paracentesis":"pbe_paracentesis"},"PERI-SEC-001":{"hemograma":"peri_cbc","pbe_cbc":"peri_cbc","chole_cbc":"peri_cbc","gasometria":"peri_gas","renal":"peri_gas","tc":"peri_ct"},"PERI-TER-001":{"hemograma":"ter_cbc","renal":"ter_cbc","tc":"ter_ct"},"APP-001":{"hemograma":"app_cbc","pbe_cbc":"app_cbc","chole_cbc":"app_cbc","tc":"app_ct","eco":"app_us"},"CHOLE-001":{"hemograma":"chole_cbc","pbe_cbc":"chole_cbc","hepatograma":"chole_liver","eco":"chole_us"},"ILEO-001":{"hemograma":"ileo_lab","renal":"ileo_lab","gasometria":"ileo_gas","tc":"ileo_ct"},"MESI-001":{"hemograma":"mesi_lab","gasometria":"mesi_gas"},"CHOLANG-001":{"hemograma":"cholang_cbc","renal":"cholang_cbc","hepatograma":"cholang_liver","eco":"cholang_us"}};
const CASE_INCIDENTAL_FINDINGS={"CHOLE-001":{"lipasa":"Lipasa sérica: elevación discreta, menor de 3 veces el límite superior de referencia. Hallazgo inespecífico, por sí solo no diagnóstico de pancreatitis aguda."}};
function csCaseStudyFallback(study,currentCase){
 const id=String(study?.id||''),caseId=String(currentCase?.id||'');
 const own=(currentCase?.studies||[]).find(s=>s.id===id);
 if(own)return own.result;
 const sourceId=CASE_STUDY_CORRELATIONS[caseId]?.[id];
 if(sourceId){
  const source=(currentCase?.studies||[]).find(s=>s.id===sourceId);
  if(source?.result)return String(study.label||id)+': hallazgos concordantes con el panel '+String(source.label||sourceId)+': '+String(source.result);
 }
 const incident=CASE_INCIDENTAL_FINDINGS[caseId]?.[id];
 if(incident)return incident;
 return study?.normalResult||null;
}

function csStudyCatalog(){const m=new Map();for(const c of CASES||[])for(const st of c.studies||[])if(st?.id&&!m.has(st.id))m.set(st.id,{id:st.id,label:st.label,aliases:[...(st.aliases||[])],type:st.type||'lab',delay:csStudyDurationMs(st)/1000,gameHours:csStudyDurationMs(st)/60000,normalResult:csNormalStudyResult(st)});return [...m.values()]}
function csStudyScore(st,n){let score=0;for(const a of [st.id,st.label,...(st.aliases||[])]){const x=norm(a);if(!x)continue;if(n===x)score=Math.max(score,10000+x.length);else if(n.includes(x))score=Math.max(score,x.length)}return score}
function findStudy(text){const n=norm(text),catalog=csStudyCatalog();let best=null,score=0;for(const st of C.studies||[]){const sc=csStudyScore(st,n);if(sc>score){best=st;score=sc}}if(best)return {...best,universalFallback:false};best=null;score=0;for(const st of catalog){const sc=csStudyScore(st,n);if(sc>score){best=st;score=sc}}return best?{...best,result:csCaseStudyFallback(best,C),universalFallback:true}:null}`;
 s=replaceOnce(s,oldFind,newFind,'universal-study-resolution');
 // Natural-language study orders share the same catalog resolver. Multiple named studies in one sentence are allowed.
 const naturalAnchor=`const i=findIntervention(raw.replace(/^orden\\s+/i,''));if(i){orderIntervention(i);return}`;
 const naturalStudy=`const csStudyIntent=/\\b(pedi|pedime|pedir|solicita|solicito|solicitar|haceme|hace|hacer|quiero|ordena|ordenar|necesito|realiza|realizar|sacame)\\b/.test(norm(raw));if(csStudyIntent&&!/[?¿]/.test(raw)&&!/(^|\\s)(no|nunca|tampoco|sin|evita|evitar|cancelar|cancela|descarta)(\\s|$)/.test(norm(raw))){const words=norm(raw).split(' ').filter(Boolean),hits=[],occupied=new Set(),seen=new Set();for(const st of [...(C.studies||[]),...csStudyCatalog()])for(const a of [st.label,...(st.aliases||[])]){const phrase=norm(a).split(' ').filter(Boolean);if(!phrase.length)continue;for(let i=0;i<=words.length-phrase.length;i++)if(phrase.every((w,j)=>words[i+j]===w))hits.push({st,start:i,end:i+phrase.length,size:phrase.length})}hits.sort((a,b)=>b.size-a.size||a.start-b.start);const chosen=[];for(const h of hits){if(seen.has(h.st.id))continue;if(Array.from({length:h.end-h.start},(_,i)=>h.start+i).some(i=>occupied.has(i)))continue;seen.add(h.st.id);for(let i=h.start;i<h.end;i++)occupied.add(i);chosen.push(h)}for(const h of chosen.sort((a,b)=>a.start-b.start))orderStudy(findStudy(h.st.label)||h.st);if(seen.size)return}const i=findIntervention(raw.replace(/^orden\\s+/i,''));if(i){orderIntervention(i);return}`;
 s=replaceOnce(s,naturalAnchor,naturalStudy,'natural-language-study-orders');
 const unknownStudy=`const i=findIntervention(raw.replace(/^orden\\s+/i,''));if(i){orderIntervention(i);return}nurseSay('No pude traducir esa orden. Probá /estudio <nombre> o /orden <conducta>.')`;
 const universalOrder=`const i=findIntervention(raw.replace(/^orden\\s+/i,''));if(i){orderIntervention(i);return}nurseSay(/^estudio\\s+/i.test(raw)?'Ese nombre no corresponde a un estudio del catálogo. Revisá el nombre e intentá de nuevo.':'Indicame el nombre del estudio o la conducta.')`;
 s=replaceOnce(s,unknownStudy,universalOrder,'free-universal-study-order');

 // Later clinical-language overlay replaces findStudy again; preserve universal resolution there.
 s=replaceOnce(s,"findStudy=function(text){return negated(language(text))||question(text)?null:match(C?.studies,text);};","findStudy=function(text){if(negated(language(text))||question(text))return null;const native=match(C?.studies,text);if(native)return native;const global=match(csStudyCatalog(),text);return global?{...global,result:csCaseStudyFallback(global,C),universalFallback:true}:null;};",'late-language-universal-study-resolution');
 // Continuous Android speech events can re-emit the same finalized result index.
 s=replaceOnce(s,"const csVoice={localActive:false,recognition:null,restarting:false,hearing:false};","const csVoice={localActive:false,recognition:null,restarting:false,hearing:false,sentFinals:new Set(),pendingByIndex:new Map(),pendingText:'',flushTimer:null,lastSentText:'',lastSentAt:0};",'speech-final-index-state');
 s=replaceOnce(s,"r.onstart=()=>{csVoice.hearing=true;csRefreshVoiceButtons()};","r.onstart=()=>{csVoice.sentFinals.clear();csVoice.pendingByIndex.clear();csVoice.pendingText='';csVoice.hearing=true;csRefreshVoiceButtons()};",'speech-new-session-reset');
 s=replaceOnce(s,"r.onresult=e=>{let final='';for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)final+=e.results[i][0].transcript+' ';if(final.trim()&&csVoice.localActive&&!csCoop.radioHeld)sendMessage(final.trim())};","r.onresult=e=>{if(!csVoice.localActive||csCoop.radioHeld)return;const update=csVoiceStageRevisions(csVoice.pendingByIndex,csVoice.sentFinals,e);csVoice.pendingText=update.text;if(update.finalCount)csVoiceReschedule()};",'speech-send-final-once');
 s=replaceOnce(s,"function csEnsureRecognition(){",[csVoiceWord,csVoiceCleanSpeech,csMergeSpeech,csVoiceNovelText,csVoiceStageRevisions,csVoiceCommitRevisions].map(fn=>fn.toString()).join('\n')+'\n'+"function csVoiceReschedule(){\n if(csVoice.flushTimer)clearTimeout(csVoice.flushTimer);\n csVoice.flushTimer=setTimeout(csVoiceFlush,1900);\n}\nfunction csVoiceFlush(){\n if(csVoice.flushTimer){clearTimeout(csVoice.flushTimer);csVoice.flushTimer=null}\n const current=csVoice.pendingByIndex.size?csVoiceCommitRevisions(csVoice.pendingByIndex,csVoice.sentFinals):csVoiceCleanSpeech(csVoice.pendingText);\n csVoice.pendingText='';\n if(!current||csCoop.radioHeld)return;\n const now=performance.now(),recent=csVoice.lastSentAt>0&&now-csVoice.lastSentAt<8000;\n const utterance=recent?csVoiceNovelText(csVoice.lastSentText,current):current;\n if(utterance)sendMessage(utterance);\n csVoice.lastSentText=recent?csMergeSpeech(csVoice.lastSentText,current):current;\n csVoice.lastSentAt=now;\n}\nfunction csVoiceQueue(text){\n csVoice.pendingText=csMergeSpeech(csVoice.pendingText,csVoiceCleanSpeech(text));\n csVoiceReschedule()\n}\n"+'function csEnsureRecognition(){','speech-reconcile-cumulative-finals');
 s=replaceOnce(s,"r.onend=()=>{csVoice.hearing=false;csRefreshVoiceButtons();if(csVoice.localActive&&!csCoop.radioHeld&&!csVoice.restarting){csVoice.restarting=true;setTimeout(()=>{csVoice.restarting=false;try{r.start()}catch(e){}},350)}};","r.onend=()=>{csVoiceFlush();csVoice.hearing=false;csRefreshVoiceButtons();if(csVoice.localActive&&!csCoop.radioHeld&&!csVoice.restarting){csVoice.restarting=true;setTimeout(()=>{csVoice.restarting=false;try{r.start()}catch(e){}},350)}};",'speech-flush-on-recognition-end');
 s=replaceOnce(s,"}else{csVoice.localActive=false;try{csVoice.recognition?.stop()}catch(e){}csUpdateMicTrack();toast('Voz local desactivada.')}","}else{csVoice.localActive=false;csVoiceFlush();try{csVoice.recognition?.stop()}catch(e){}csUpdateMicTrack();toast('Voz local desactivada.')}",'speech-flush-on-mic-off');
 let direct=0;s=s.replace(/s\.delay\*1000/g,()=>{direct++;return 'csStudyDurationMs(s)'});if(direct!==1)throw new Error('direct study timing anchor expected 1, got '+direct);
 let lab=0;s=s.replace(/t\.study\.delay\*1000/g,()=>{lab++;return 'csStudyDurationMs(t.study)'});if(lab!==1)throw new Error('lab study timing anchor expected 1, got '+lab);
 const socialExport=`window.nsSocial={state,render,health,connect,register,search,refresh,addFriend:id=>friendAction('friends',id),acceptFriend:id=>friendAction('friends/accept',id),declineFriend:id=>friendAction('friends/decline',id),createRoom,inviteToRoom,joinRoom,declineRoom,removeInvite,cancelRoom,leave,role:()=>room?.role||null,room:()=>room};`;
 const socialExportSafe=`window.nsSocial={state,render,health,connect,register,ensureSession:async()=>{const data=await acquireSession();await refresh();return data.user},search,refresh,addFriend:id=>friendAction('friends',id),acceptFriend:id=>friendAction('friends/accept',id),declineFriend:id=>friendAction('friends/decline',id),createRoom,inviteToRoom,joinRoom,declineRoom,removeInvite,cancelRoom,leave,role:()=>room?.role||null,room:()=>room};`;
 s=replaceOnce(s,socialExport,socialExportSafe,'single-social-session-owner');
 s=replaceOnce(s,"function statePayload(){return{peerId:csV41Challenge?.selfId||'local',x:player.x","function statePayload(){let pid=sessionStorage.getItem('atria.lobby.peer.v2');if(!pid){pid='L_'+Math.random().toString(36).slice(2)+Date.now().toString(36);sessionStorage.setItem('atria.lobby.peer.v2',pid)}return{peerId:pid,x:player.x",'lobby-unique-peer-id-for-network-presence');
 s=replaceOnce(s,"function peerId(){\n    try{\n      if(window.csV41Challenge&&window.csV41Challenge.selfId)return String(window.csV41Challenge.selfId);\n      var k='atria.lobby.peer.v2',v=sessionStorage.getItem(k);\n      if(!v){v='L_'+Math.random().toString(36).slice(2)+Date.now().toString(36);sessionStorage.setItem(k,v)}\n      return v;\n    }catch(_){return 'L_'+Math.random().toString(36).slice(2)}\n  }\n  ","function peerId(){\n    try{\n      if(!window.nsLobby?.active&&window.csV41Challenge&&window.csV41Challenge.selfId)return String(window.csV41Challenge.selfId);\n      var k='atria.lobby.peer.v2',v=sessionStorage.getItem(k);\n      if(!v){v='L_'+Math.random().toString(36).slice(2)+Date.now().toString(36);sessionStorage.setItem(k,v)}\n      return v;\n    }catch(_){return 'L_'+Math.random().toString(36).slice(2)}\n  }\n  ",'lobby-rtc-unique-session-peer');
 s=replaceOnce(s,"const data=await lobbyApi('lobby?after='+state.cursor);if(!state.active||C||sim||epoch!==state.epoch)return;","const data=await lobbyApi('lobby?after='+state.cursor);state._lastServerPollAt=Date.now();state._lastServerPollError=null;if(!state.active||C||sim||epoch!==state.epoch)return;",'lobby-true-poll-timestamp');
 s=replaceOnce(s,"}catch(err){state.status='Lobby reconectando…';renderHud()}finally{state.polling=false}","}catch(err){state._lastServerPollError=String(err?.message||err||'error de conexión');state.status='Lobby reconectando…';renderHud()}finally{state.polling=false}",'lobby-server-poll-errors');
 s=replaceOnce(s,"window.nsLobby.enter=enter;window.nsLobby.renderHud=renderHud;window.nsLobby.renderChat=renderChat;window.nsLobby.openGuardia=openGuardia;window.nsLobby.openPeople=openPeople;","window.nsLobby.enter=enter;window.nsLobby.renderHud=renderHud;window.nsLobby.renderChat=renderChat;window.nsLobby.openGuardia=openGuardia;window.nsLobby.openPeople=openPeople;\nwindow.nsLobbyTransportDiagnostics=()=>{const s=social();return {active:state.active,backendAvailable:!!s.available,backendOrigin:s.endpoint||null,authenticated:!!s.user,serverPollAgeMs:state._lastServerPollAt?Date.now()-state._lastServerPollAt:null,lastServerPollError:state._lastServerPollError||null,visiblePlayers:state.players.size,onlinePlayers:[...state.players.values()].filter(p=>p.online!==false).length,rtc:window.nsLobbyNetStats?.()||null}};",'lobby-transport-readonly-diagnostics');
 s=replaceOnce(s,"async function waitForPartyTransport(roomId){for(let i=0;i<40;i++){if(!state.groupPlan||state.groupPlan.roomId!==roomId)return false;const r=social().room,members=r?.members?.length||0;if(r?.allAccepted&&members>=2){if(csCoop?.connected)return true;await new Promise(res=>setTimeout(res,180));const rr=social().room;if(rr?.allAccepted&&(rr.members?.length||0)>=2){try{csCoop.connected=true}catch(_){}return true}}await new Promise(res=>setTimeout(res,250))}return false}","function roomTransportReady({room,localUserId,connected,channelState}){\n return !!(room?.allAccepted && Array.isArray(room.members) && room.members.length>=2 &&\n room.members.some(p=>p?.userId!==localUserId && p?.online===true) &&\n connected===true && channelState==='open');\n}\n\nasync function waitForPartyTransport(roomId){for(let attempt=0;attempt<40;attempt++){if(!state.groupPlan||state.groupPlan.roomId!==roomId||!state.active)return false;const r=social().room;if(roomTransportReady({room:r,localUserId:uid(),connected:csCoop?.connected,channelState:csCoop?.dc?.readyState}))return true;await new Promise(res=>setTimeout(res,250))}return false}",'party-transport-live-state-requirement');
 s=replaceOnce(s,"if(!r||r.role!=='host'||!p||p.roomId!==r.id||p.started||p.starting||!r.allAccepted||(r.members?.length||0)<2)return;","if(!r||r.role!=='host'||!p||p.roomId!==r.id||p.started||p.starting||!r.allAccepted||(r.members?.length||0)<2||(p.transportRetryAfter&&Date.now()<p.transportRetryAfter))return;",'party-start-backoff-until-live');
 s=replaceOnce(s,"if(!connected){p.starting=false;state.status='Grupo listo · terminando de conectar…';renderHud();return}","if(!connected){p.starting=false;p.transportRetryAfter=Date.now()+15000;state.status='No se confirmó conexión con los compañeros. La sala sigue abierta: reintentá cuando estén en línea.';renderHud();return}",'party-retry-visible-error');
 s=replaceOnce(s,"if(state.groupPlan)state.groupPlan.starting=false;maybeAutoStart()","if(state.groupPlan){state.groupPlan.starting=false;state.groupPlan.transportRetryAfter=0}maybeAutoStart()",'party-manual-retry');
 s=replaceOnce(s,"csCoop.connected=opened&&peers.length>0;if(peers.length&&!opened){opened=true;dc.readyState='open';dc.onopen?.()}if(peers.length)status=peers.length===1?'Conectado con '+peers[0].name:peers.length+' compañeros conectados';else status='Guardia lista · invitá amigos'","csCoop.connected=opened&&live.length>0;if(live.length&&!opened){opened=true;dc.readyState='open';dc.onopen?.()}if(live.length)status=live.length===1?'Conectado con '+live[0].name:live.length+' compañeros conectados';else status=peers.length?'Esperando compañeros en línea…':'Guardia lista · invitá amigos'",'party-connected-only-live-peers');
 s=replaceOnce(s,"results=s.results||[],room=s.room;let html=","results=s.results||[],room=s.room,presenceVerified=!!state._lastServerPollAt&&!state._lastServerPollError&&(Date.now()-state._lastServerPollAt<15000);let html=",'friends-require-fresh-backend-presence');
 s=replaceOnce(s,"else{html+=`<div class=\"nsPeopleAlias\">Conectado como <b>@${e(s.user.handle)}</b></div>`;if(room){","else{html+=`<div class=\"nsPeopleAlias\">Conectado como <b>@${e(s.user.handle)}</b></div>`;if(!presenceVerified)html+='<div class=\"nsPeopleOffline\">Amigos guardados disponibles. No se pudo verificar quién está conectado en el lobby; la presencia se actualizará al restablecer el servidor.</div>';if(room){",'friends-show-server-presence-warning');
 s=replaceOnce(s,"return peopleRow(p,acts)}).join(''):'<div class=\"nsPeopleEmpty\">Todavía no tienes amigos.","return peopleRow(p,acts,presenceVerified?null:('@'+e(p.handle||'jugador')+' · presencia sin verificar'))}).join(''):'<div class=\"nsPeopleEmpty\">Todavía no tienes amigos.",'friends-cache-never-falsely-online');
 // Social bootstrap is idempotent: acquire/resume the profile instead of racing a second registration.
 const oldEnsureSocial=`async function ensureSocial(){try{await nsSocial?.health?.();let s=social();if(!s.available){state.status='Lobby local · el servidor social no está conectado.';return false}if(!s.user){const raw=(csProfile?.name||'medico').normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'').slice(0,22)||'medico';const alias=raw.length>=3?raw:(raw+'_med').slice(0,22);try{await nsSocial.register(alias)}catch(err){state.status='Reconectando tu perfil · '+(err?.message||'sin conexión');return false}s=social()}await nsSocial.refresh();return true}catch(err){state.status='Lobby local · '+(err?.message||'sin conexión');return false}}`;
 const newEnsureSocial=`async function ensureSocial(){try{await nsSocial?.health?.();let s=social();if(!s.available){state.status='Lobby local · el servidor social no está conectado.';return false}if(!s.user){await nsSocial.ensureSession();s=social()}if(!s.user){state.status='Lobby local · perfil social no disponible.';return false}await nsSocial.refresh();return true}catch(err){console.warn('ATRIA social bootstrap',err);state.status='Lobby local · conexión social temporalmente no disponible.';return false}}`;
 s=replaceOnce(s,oldEnsureSocial,newEnsureSocial,'idempotent-social-bootstrap');
 s=replaceOnce(s,"  window.fetch=async function(input,init){\n    try{\n      var raw=typeof input==='string'?input:(input&&input.url)||'',u=new URL(raw,location.href);\n      var method=String((init&&init.method)||((input&&input.method)||'GET')).toUpperCase();\n      if(u.origin===location.origin&&u.pathname==='/api/lobby/state'&&method==='POST'){\n        var now=performance.now();\n        if(now-net.lastLegacyState<5000)return new Response(JSON.stringify({ok:true,transport:'rtc'}),{status:200,headers:{'Content-Type':'application/json'}});\n        net.lastLegacyState=now;return originalFetch(input,init);\n      }\n      if(u.origin===location.origin&&u.pathname==='/api/lobby'&&method==='GET'){\n        var now2=performance.now();\n        if(now2-net.lastLegacyLobby<2400)return new Response(JSON.stringify({players:legacyPlayers([]),messages:[],cursor:Number(u.searchParams.get('after')||0)}),{status:200,headers:{'Content-Type':'application/json'}});\n        net.lastLegacyLobby=now2;\n        try{\n          var rr=await originalFetch(input,init),d=await rr.clone().json();mergeRoster(d.players||[]);d.players=legacyPlayers(d.players||[]);\n          return new Response(JSON.stringify(d),{status:rr.status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});\n        }catch(_){return new Response(JSON.stringify({players:legacyPlayers([]),messages:[],cursor:Number(u.searchParams.get('after')||0)}),{status:200,headers:{'Content-Type':'application/json'}})}\n      }\n    }catch(_){}\n    return originalFetch(input,init);\n  };\n\n","  // Leave window.fetch unchanged: the authenticated lobby API is authoritative.\\n  // RTC merely accelerates position updates, never fabricates HTTP responses.\\n\\n",'lobby-remove-fabricated-fetch-responses');
 s=replaceOnce(s,"if(!state.demo&&!state.polling&&(state._lastPoll||0)+320<t)","if(!state.demo&&!state.polling&&(state._lastPoll||0)+900<t)",'lobby-bounded-server-poll');
 s=replaceOnce(s,"  async function discovery(){\n    if(net.discovering||!window.nsLobby||!window.nsLobby.active)return;\n    net.discovering=true;\n    try{\n      var p=localState();\n      var jobs=[p?api('POST',{presence:p}):Promise.resolve(null),api('GET',null,'?roster=1')];\n      var rr=await Promise.allSettled(jobs);\n      if(rr[1]&&rr[1].status==='fulfilled'){var d=rr[1].value;mergeRoster(d.players||[])}\n    }catch(_){}finally{net.discovering=false}\n  }\n","  async function discovery(){\n    if(net.discovering||!window.nsLobby||!window.nsLobby.active||performance.now()<(net.retryAt||0))return;\n    net.discovering=true;\n    try{\n      // RTC is an OPTIONAL accelerator. Never fabricate network success or block the social lobby.\n      // Check GET first, so an unhealthy signaling service is not hit with redundant POST writes.\n      var d=await api('GET',null,'?roster=1');\n      if(!Array.isArray(d.players))throw Error('RTC roster missing players');\n      mergeRoster(d.players);net.syncFailures=0;net.retryAt=0;net.lastSyncError=null;\n      var p=localState();if(p)api('POST',{presence:p}).catch(function(e){net.lastPostError=String(e?.message||e)});\n    }catch(err){\n      net.syncFailures=Math.min(6,(net.syncFailures||0)+1);\n      net.retryAt=performance.now()+Math.min(60000,5000*Math.pow(2,net.syncFailures-1));\n      net.lastSyncError=String(err?.message||err);\n    }finally{net.discovering=false}\n  }\n",'rtc-roster-500-bounded-backoff-and-server-first');
 s=replaceOnce(s,"window.nsLobbyNetStats=function(){return {version:net.version,id:myId(),remotes:net.remotes.size,roster:net.roster.size,peers:window.nsLobbyRtcStats()}};","window.nsLobbyNetStats=function(){return {version:net.version,remotes:net.remotes.size,roster:net.roster.size,syncFailures:net.syncFailures||0,retryInMs:Math.max(0,Math.ceil((net.retryAt||0)-performance.now())),lastSyncError:net.lastSyncError||null,peers:window.nsLobbyRtcStats()}};",'rtc-readonly-health-diagnostics');
 // The legacy RTC lobby installed a second permanent RAF/network scheduler. Keep one owner: nsLobby tick.
 const rtcStatsAnchor=`window.nsLobbyRtcStats=function(){var out=[];net.peers.forEach(function(r,id){out.push({id:id,peerId:r.peerId,open:!!r.open,connecting:!!r.connecting,state:r.pc&&r.pc.connectionState||'none',channel:r.dc&&r.dc.readyState||'none'})});return out};`;
 const rtcStatsSafe=rtcStatsAnchor+`\n  window.nsLobbyRtcStop=function(){net.peers.forEach(function(r){try{if(r.dc)r.dc.close()}catch(_){}try{if(r.pc)r.pc.close()}catch(_){}});net.peers.clear();net.roster.clear();net.remotes.clear();net.discovering=false;net.lastDiscovery=0;net.lastRtcSend=0;net.lastFrame=0};`;
 s=replaceOnce(s,rtcStatsAnchor,rtcStatsSafe,'rtc-lobby-cleanup');
 const deactivateAnchor=`function deactivate({notify=true}={}){state.epoch++;if(!state.active)return;state.active=false;`;
 s=replaceOnce(s,deactivateAnchor,`function deactivate({notify=true}={}){state.epoch++;if(!state.active)return;state.active=false;window.nsLobbyRtcStop?.();`,'rtc-cleanup-on-lobby-leave');
 const rtcStart=`setTimeout(discovery,250);requestAnimationFrame(animate);`;
 s=replaceOnce(s,rtcStart,`// RTC discovery is driven conservatively from the primary lobby scheduler; no second permanent RAF.\n  window.nsLobbyRtcPulse=function(ts){if(!window.nsLobby?.active)return;ts=Number(ts)||performance.now();if(ts-net.lastRtcSend>=220){net.lastRtcSend=ts;var p=localState();if(p)sendRtc(p)}if(ts-net.lastDiscovery>=2500){net.lastDiscovery=ts;discovery()}};`,'single-lobby-scheduler');
 const socialPulse=`if((state._lastSocial||0)+1000<t){state._lastSocial=t;nsSocial?.refresh?.().then(()=>{renderHud();if(document.getElementById('nsLobbyGuard')?.classList.contains('show')&&social().room)openWaitingRoom()}).catch(()=>{})}`;
 s=replaceOnce(s,socialPulse,`if((state._lastSocial||0)+2500<t){state._lastSocial=t;nsSocial?.refresh?.().then(()=>{renderHud();if(document.getElementById('nsLobbyGuard')?.classList.contains('show')&&social().room)openWaitingRoom()}).catch(()=>{})}window.nsLobbyRtcPulse?.(t)`,'bounded-social-rtc-pulse');
 const activationText='Activa una vez tu perfil social. El alias parte del nombre de tu personaje.';
 const activationAt=s.indexOf(activationText);if(activationAt<0)throw new Error('integration anchor missing: people-auto-presence');
 const activationStart=s.lastIndexOf("else if(!s.user){",activationAt),activationEnd=s.indexOf("}\n else{",activationAt);if(activationStart<0||activationEnd<0)throw new Error('integration anchor malformed: people-auto-presence');
 s=s.slice(0,activationStart)+"else if(!s.user){html+='<div class=\"nsPeopleOffline\">Conectando tu perfil automáticamente…</div>';nsSocial?.ensureSession?.().then(()=>{if(document.getElementById('nsPeopleModal')?.classList.contains('show'))openPeople()}).catch(()=>{})}"+s.slice(activationEnd+1);
 // Smooth the legacy 220 ms guard-network snapshots at render cadence instead of drawing raw packet positions.
 const rawRemote=`function csDrawRemote(){
 const r=csCoop.remote;if(!csCoop.connected||!r||!C||r.caseId!==C.id)return;
 const key=r.coat?'coat':(r.color||'navy'),im=csVariantImgs[key]||csVariantImgs.navy;if(!im?.complete)return;
 const actor={x:r.x||0,y:r.y||0,dir:r.dir||'S',moving:!!r.moving,walkPhase:r.walkPhase||0};drawSprite(im,actor,60);csDrawNameplate(actor,r.name||'Compañero',r.level||1,true)
}`;
 const smoothRemote=`let csRemotePose=null;
function csRemoteVisual(r,now=performance.now()){if(!csRemotePose){csRemotePose={x:Number(r.x)||0,y:Number(r.y)||0,fromX:Number(r.x)||0,fromY:Number(r.y)||0,toX:Number(r.x)||0,toY:Number(r.y)||0,at:now}}if(csRemotePose.toX!==(Number(r.x)||0)||csRemotePose.toY!==(Number(r.y)||0)){const p=csRemoteVisualSample(now);csRemotePose={x:p.x,y:p.y,fromX:p.x,fromY:p.y,toX:Number(r.x)||0,toY:Number(r.y)||0,at:now}}return csRemoteVisualSample(now)}
function csRemoteVisualSample(now=performance.now()){const p=csRemotePose;if(!p)return{x:0,y:0};const t=Math.max(0,Math.min(1,(now-p.at)/220)),e=t*t*(3-2*t);return{x:p.fromX+(p.toX-p.fromX)*e,y:p.fromY+(p.toY-p.fromY)*e}}
function csDrawRemote(){
 const r=csCoop.remote;if(!csCoop.connected||!r||!C||r.caseId!==C.id){csRemotePose=null;return}
 const key=r.coat?'coat':(r.color||'navy'),im=csVariantImgs[key]||csVariantImgs.navy;if(!im?.complete)return;
 const p=csRemoteVisual(r),actor={x:p.x,y:p.y,dir:r.dir||'S',moving:!!r.moving,walkPhase:r.walkPhase||0};drawSprite(im,actor,60);csDrawNameplate(actor,r.name||'Compañero',r.level||1,true)
}`;
 s=replaceOnce(s,rawRemote,smoothRemote,'guard-remote-interpolation');
 // Shared 2-4 player rooms override the legacy renderer/sender later in the golden master.
 // Wire smoothing/backpressure into that actual override as well, keyed per peer.
 const sharedWireOld=`if(parsed?.type==='state'&&parsed.roomId===challenge.id&&parsed.name){csCoop.remotes=csCoop.remotes||{};const pid=parsed.peerId||parsed._fromPeerId;if(pid)csCoop.remotes[pid]={...(csCoop.remotes[pid]||{}),...parsed,online:true}}`;
 const sharedWireNew=`if(parsed?.type==='state'&&parsed.roomId===challenge.id&&parsed.name){csCoop.remotes=csCoop.remotes||{};const pid=parsed.peerId||parsed._fromPeerId;if(pid){const prev=csCoop.remotes[pid],seq=Number(parsed.stateSeq)||0;if(!prev||!seq||seq>Number(prev.stateSeq||0))csCoop.remotes[pid]={...(prev||{}),...parsed,online:true}}}`;
 s=replaceOnce(s,sharedWireOld,sharedWireNew,'shared-room-stale-state-rejection');
 const sharedSendOld=`csSendPeerState=function(){if(!shared())return oldPeerSend.apply(this,arguments);const p=ownsCurrent()?currentPatient():null;try{if(csCoop?.dc?.readyState==='open')csCoop.dc.send(JSON.stringify({type:'state',peerId:selfId,roomId:challenge.id,x:player.x,y:player.y,dir:player.dir,moving:player.moving,walkPhase:player.walkPhase,name:name(),level:csLevel(),color:csProfile?.scrubColor,coat:!!(csProfile?.coatUnlocked&&csProfile?.coatEquipped),caseId:p?.caseId||null,patientUid:p?.uid||null,patientName:p?.instance?.name||null,patientAge:p?.instance?.age||null,bedId:p?.instance?.bedId||null,bedLabel:p?.instance?.bed?.label||null,assignmentMode:challenge.mode,radio:!!csCoop.radioHeld,voice:!!csVoice.localActive}))}catch(_){}};`;
 const sharedSendNew=`let csSharedStateSeq=0;const csSharedRemotePose=new Map();csSendPeerState=function(){if(!shared())return oldPeerSend.apply(this,arguments);const p=ownsCurrent()?currentPatient():null;try{if(csCoop?.dc?.readyState==='open'&&(csCoop.dc.bufferedAmount||0)<=65536)csCoop.dc.send(JSON.stringify({type:'state',stateSeq:++csSharedStateSeq,peerId:selfId,roomId:challenge.id,x:player.x,y:player.y,dir:player.dir,moving:player.moving,walkPhase:player.walkPhase,name:name(),level:csLevel(),color:csProfile?.scrubColor,coat:!!(csProfile?.coatUnlocked&&csProfile?.coatEquipped),caseId:p?.caseId||null,patientUid:p?.uid||null,patientName:p?.instance?.name||null,patientAge:p?.instance?.age||null,bedId:p?.instance?.bedId||null,bedLabel:p?.instance?.bed?.label||null,assignmentMode:challenge.mode,radio:!!csCoop.radioHeld,voice:!!csVoice.localActive}))}catch(_){}};`;
 s=replaceOnce(s,sharedSendOld,sharedSendNew,'shared-room-state-backpressure-sequence');
 const sharedDrawOld=`csDrawRemote=function(){if(!shared())return oldRemoteDraw.apply(this,arguments);const remotes=Object.values(csCoop.remotes||{});for(const r of remotes){if(!r||r.roomId!==challenge.id)continue;const im=csVariantImgs[r.coat?'coat':r.color||'navy']||csVariantImgs.navy;if(!im?.complete)continue;const actor={x:r.x||0,y:r.y||0,dir:r.dir||'S',moving:!!r.moving,walkPhase:r.walkPhase||0};drawSprite(im,actor,60);csDrawNameplate(actor,r.name||'Compañero',r.level||1,true)}};`;
 const sharedDrawNew=`csDrawRemote=function(){if(!shared()){csSharedRemotePose.clear();return oldRemoteDraw.apply(this,arguments)}const now=performance.now(),remotes=Object.values(csCoop.remotes||{}),live=new Set();for(const r of remotes){if(!r||r.roomId!==challenge.id)continue;const id=String(r.peerId||r._fromPeerId||r.userId||r.name||'remote');live.add(id);let p=csSharedRemotePose.get(id);const tx=Number(r.x)||0,ty=Number(r.y)||0;if(!p)p={x:tx,y:ty,fromX:tx,fromY:ty,toX:tx,toY:ty,at:now};if(p.toX!==tx||p.toY!==ty){const t=Math.max(0,Math.min(1,(now-p.at)/220)),e=t*t*(3-2*t),x=p.fromX+(p.toX-p.fromX)*e,y=p.fromY+(p.toY-p.fromY)*e;p={x,y,fromX:x,fromY:y,toX:tx,toY:ty,at:now}}const t=Math.max(0,Math.min(1,(now-p.at)/220)),e=t*t*(3-2*t);p.x=p.fromX+(p.toX-p.fromX)*e;p.y=p.fromY+(p.toY-p.fromY)*e;csSharedRemotePose.set(id,p);const im=csVariantImgs[r.coat?'coat':r.color||'navy']||csVariantImgs.navy;if(!im?.complete)continue;const actor={x:p.x,y:p.y,dir:r.dir||'S',moving:!!r.moving,walkPhase:r.walkPhase||0};drawSprite(im,actor,60);csDrawNameplate(actor,r.name||'Compañero',r.level||1,true)}for(const id of csSharedRemotePose.keys())if(!live.has(id))csSharedRemotePose.delete(id)};`;
 s=replaceOnce(s,sharedDrawOld,sharedDrawNew,'shared-room-per-peer-interpolation');
 const oldPeer=`function csSendPeerState(){\n if(!csCoop.dc||csCoop.dc.readyState!=='open'||!csProfile)return;`;
 const newPeer=`function csSendPeerState(){\n if(!csCoop.dc||csCoop.dc.readyState!=='open'||!csProfile)return;\n if((csCoop.dc.bufferedAmount||0)>65536)return;`;
 s=replaceOnce(s,oldPeer,newPeer,'peer-backpressure');
 const disabledVoice=` // Player radio needs a voice transport; this release provides clinical data and text only.\n const refreshVoice=csRefreshVoiceButtons;\n csRefreshVoiceButtons=function(){const r=refreshVoice.apply(this,arguments),b=document.getElementById('radioPttBtn');if(b){b.disabled=true;b.hidden=true;b.title='La sala comparte texto y acciones. Radio de voz pendiente.';}return r;};\n csRefreshVoiceButtons();`;
 s=replaceOnce(s,disabledVoice,` // Existing WebRTC audio transport is enabled; task13 handles mic permission priming.\n csRefreshVoiceButtons();`,'social-voice-enable');
 // VoiceV2 (later in the 4.8.6 document) overrides the original mic.
 // Revise the *active* Android recognizer, not only the superseded csVoice.
 s=replaceOnce(s,"const VoiceV2={active:false,rec:null,permissionChecked:false,lastInterim:''};","const VoiceV2={active:false,rec:null,permissionChecked:false,lastInterim:'',pendingByIndex:new Map(),delivered:new Set(),committed:false,aborted:false,commitTimer:null};",'android-v2-index-buffer');
 const v2Start=s.indexOf('    r.onresult=(ev)=>{'),v2End=s.indexOf('    r.onerror=(ev)=>{',v2Start);
 if(v2Start<0||v2End<0||s.indexOf('    r.onresult=(ev)=>{',v2Start+1)>=0)throw new Error('Android VoiceV2 handler anchor missing or ambiguous');
 s=s.slice(0,v2Start)+"    r.onresult=(ev)=>{\n      if(VoiceV2.rec!==r||VoiceV2.committed||VoiceV2.aborted)return;\n      const update=csVoiceStageRevisions(VoiceV2.pendingByIndex,VoiceV2.delivered,ev);\n      let interim='';\n      for(let i=0;i<ev.results.length;i++)if(!ev.results[i].isFinal){\n        const t=String(ev.results[i][0]?.transcript||'').trim();\n        if(t)interim=csMergeSpeech(interim,t);\n      }\n      VoiceV2.lastInterim=interim;\n      voiceUIV2(true,interim||update.text);\n      if(update.finalCount){\n        if(VoiceV2.commitTimer)clearTimeout(VoiceV2.commitTimer);\n        VoiceV2.commitTimer=setTimeout(voiceV2Commit,6000);\n      }\n    };\n"+s.slice(v2End);
 s=replaceOnce(s,'  async function startVoiceV2(){','  '+"function voiceV2Commit(){\n    if(VoiceV2.committed||VoiceV2.aborted)return;\n    if(VoiceV2.commitTimer){clearTimeout(VoiceV2.commitTimer);VoiceV2.commitTimer=null}\n    const final=csVoiceCommitRevisions(VoiceV2.pendingByIndex,VoiceV2.delivered);\n    const phrase=csVoiceCleanSpeech(final||VoiceV2.lastInterim);\n    VoiceV2.committed=true;VoiceV2.lastInterim='';\n    if(phrase&&!csCoop.radioHeld){\n      const inp=document.getElementById('dieInput');if(inp)inp.value='';\n      sendMessage(phrase);try{csPlaySound('ok')}catch(e){}\n    }\n  }\n  "+'async function startVoiceV2(){','android-v2-single-commit-helper');
 s=replaceOnce(s,"VoiceV2.rec=r; VoiceV2.active=true; VoiceV2.lastInterim=''; VoiceV2.sentThisTurn=false;","VoiceV2.rec=r; VoiceV2.active=true; VoiceV2.lastInterim=''; VoiceV2.committed=false;VoiceV2.aborted=false;VoiceV2.pendingByIndex.clear();VoiceV2.delivered.clear();if(VoiceV2.commitTimer)clearTimeout(VoiceV2.commitTimer);VoiceV2.commitTimer=null;",'android-v2-turn-reset');
 s=replaceOnce(s,"    VoiceV2.active=false;\n    try { if(r) cancel?r.abort():r.stop(); } catch(e) {}","    VoiceV2.active=false;VoiceV2.aborted=!!cancel;\n    if(cancel&&VoiceV2.commitTimer){clearTimeout(VoiceV2.commitTimer);VoiceV2.commitTimer=null}\n    try { if(r) cancel?r.abort():r.stop(); } catch(e) {}",'android-v2-cancel');
 s=replaceOnce(s,"      VoiceV2.active=false;voiceUIV2(false);\n      if(code!=='aborted')","      VoiceV2.active=false;VoiceV2.aborted=true;if(VoiceV2.commitTimer){clearTimeout(VoiceV2.commitTimer);VoiceV2.commitTimer=null}voiceUIV2(false);\n      if(code!=='aborted')",'android-v2-error');
 s=replaceOnce(s,"    r.onerror=(ev)=>{\n      const code=","    r.onerror=(ev)=>{\n      if(VoiceV2.rec!==r)return;\n      const code=",'android-v2-stale-error');
 s=replaceOnce(s,"r.onend=()=>{const fallback=!VoiceV2.sentThisTurn?String(VoiceV2.lastInterim||'').trim():'';VoiceV2.active=false;voiceUIV2(false);if(fallback.length>1){sendMessage(fallback);VoiceV2.sentThisTurn=true;}};","r.onend=()=>{if(VoiceV2.rec!==r)return;voiceV2Commit();VoiceV2.active=false;voiceUIV2(false)};",'android-v2-single-send-end');
 // Resolve exact anamnesis intentions before fuzzy keywords and case-specific symptom scoring.
 s=replaceOnce(s,'function patientReply(q){',
   [csAnamnesisClassify,csAnamnesisFact].map(fn=>fn.toString()).join('\n')+'\n'+
   "function patientReply(q){\n const fact=csAnamnesisFact(C,q);if(fact){if(!fact.text)return 'No recuerdo ese dato, doctor. ¿Me puede preguntar de otra manera?';if(!sim.intentHistory.some(h=>h.id==='anamnesis:'+fact.intent))sim.intentHistory.push({id:'anamnesis:'+fact.intent,reveal:fact.intent+': '+fact.text,source:fact.source,caseId:C.id});complete('talk');return fact.text;}",
   'live-patient-case-bound-anamnesis');
 // Prevent a response queued in box A from being delivered to box B.
 s=replaceOnce(s,
   "function deliverPatientSpeech(text,localMode=false){sim.chats.patient.push(['doctor',text]);const a=patientReply(text);setTimeout(()=>{if(!sim||sim.caseEnded)return;",
   "function deliverPatientSpeech(text,localMode=false){const activeSim=sim,activeCase=C;sim.chats.patient.push(['doctor',text]);const a=patientReply(text);setTimeout(()=>{if(!sim||sim!==activeSim||C!==activeCase||sim.caseEnded)return;",
   'patient-delayed-answer-case-isolation');
 return s;
}
