import assert from'node:assert/strict';import vm from'node:vm';import fs from'node:fs';import{apply487}from'./apply-487.js';
const src=fs.readFileSync('vendor/atria-4.8.6/index.html','utf8'),out=apply487(src);
assert.match(out,/function csStudyCatalog\(\)/,'artifact must build one universal catalog from all case study definitions');
assert.match(out,/function csNormalStudyResult\(st\)/,'artifact must provide a normal fallback for every catalog entry');
assert.match(src,/task7\.js\?v=483/,'golden master must retain legacy task7 fallback loader');
assert.doesNotMatch(out,/task7\.js\?v=483/,'4.8.7 artifact must not load superseded task7 study fallback');
assert.match(src,/task8\.js\?v=482/,'golden master must retain legacy task8 loader');
assert.match(src,/task12\.js\?v=485/,'golden master must retain legacy task12 loader');
assert.doesNotMatch(out,/task8\.js\?v=482/,'4.8.7 artifact must not load legacy task8 DOM poller');
assert.doesNotMatch(out,/task12\.js\?v=485/,'4.8.7 artifact must not load legacy task12 DOM poller');
assert.match(src,/task13\.js\?v=486/,'golden master must retain task13 PTT primer');
assert.doesNotMatch(out,/task13\.js\?v=486/,'4.8.7 artifact must not load task13 because its capture handler preempts task5 group voice');
assert.match(out,/task5\.js\?v=475/,'task5 automatic lobby\/room group voice must remain loaded');
assert.match(out,/universalFallback:true/);
assert.doesNotMatch(out,/id:'universal_'/,'unknown names must never create invented studies');
assert.match(out,/Ese nombre no corresponde a un estudio del catálogo/,'only genuinely unknown studies may be rejected');
assert.doesNotMatch(out,/No pude traducir esa orden/,'recognized study commands must not fall into legacy response');
const orderUpdate=out.match(/function updateOrders\(\)\{[\s\S]*?\}\}\nfunction updateSimulation/)?.[0]||'';
assert.doesNotMatch(orderUpdate,/o\.result/,'study completion notification must not reveal result content');
assert.match(orderUpdate,/Resultado disponible: /,'study completion may record availability only');
const background=out.match(/function csBackgroundResultsV203\(\)\{[\s\S]*?setInterval\(csBackgroundResultsV203/)?.[0]||'';
assert.doesNotMatch(background,/o\.result/,'inactive-patient completion notification must not reveal result content');
assert.match(background,/resultado\$\{newResults===1\?'':'s'\} disponible/,'background notification must announce availability only');
const historyView=out.match(/function historyHTML\(\)\{[\s\S]*?\}\nfunction studiesHTML/)?.[0]||'';
assert.doesNotMatch(historyView,/o\.result/,'chart/history must not reveal study result content');
assert.match(historyView,/Consultá la pestaña Estudios/,'chart must direct the player to Studies for result content');
const studiesView=out.match(/function studiesHTML\(\)\{[\s\S]*?\}\nfunction examHTML/)?.[0]||'';
assert.match(studiesView,/o\.result/,'Studies tab must remain the place that renders result content');
assert.equal((out.match(/\*60000/g)||[]).length>=2,true,'study turnaround must use 1 real minute per game hour');
assert.match(out,/csCoop\.dc\.bufferedAmount\|\|0\)>65536/);
assert.equal(out.includes('s.delay*1000'),false,'legacy seconds-scale study timing must be gone');
assert.equal(src.includes('universalFallback:true'),false,'golden master must remain immutable');
assert.doesNotMatch(out,/Radio de voz pendiente/,'candidate must not intentionally disable existing WebRTC voice transport');
assert.match(src,/Radio de voz pendiente/,'golden master remains unchanged while candidate removes the disable gate');
assert.match(out,/atria-boot-paint-guard/,'first paint must be guarded before legacy HUD can flash');
assert.match(out,/classList\.add\('atriaBootReady'\)/,'boot guard must release only after splash creation');
assert.doesNotMatch(out,/Reconectando tu perfil/,'automatic social bootstrap must not expose legacy re-registration failure state');
assert.match(out,/window\.nsLobbyRtcPulse=function/,'RTC must be scheduled by the primary lobby lifecycle');
assert.doesNotMatch(out,/setTimeout\(discovery,250\);requestAnimationFrame\(animate\)/,'duplicate permanent RTC RAF must be removed');
assert.match(out,/\+2500<t/,'social refresh must be bounded in the lobby scheduler');
assert.doesNotMatch(out,/Activa una vez tu perfil social/,'People must never require manual social activation');
assert.doesNotMatch(out,/>Activar<\/button>/,'manual social activation control must be removed');
assert.match(out,/Conectando tu perfil automáticamente/,'People should represent automatic presence bootstrap');
assert.match(out,/ensureSession:async\(\)=>\{const data=await acquireSession\(\);await refresh\(\);return data\.user\}/,'social module must expose one idempotent session owner');
assert.match(out,/await nsSocial\.ensureSession\(\)/,'lobby bootstrap must use the shared session owner');
assert.doesNotMatch(out,/nsSocial\?\.register\?\.\(\)\.then/,'People must not race a second registration caller');
assert.equal((out.match(/window\.nsLobbyRtcPulse=function/g)||[]).length,1,'integrated artifact must have exactly one RTC pulse owner');
assert.equal((out.match(/ensureSession:async/g)||[]).length,1,'integrated artifact must have exactly one exported social session owner');
assert.match(out,/lastRtcSend>=220/,'RTC state sends must be throttled');
assert.match(out,/lastDiscovery>=2500/,'RTC discovery must be bounded');
assert.match(out,/bufferedAmount\|\|0\)>65536/,'shared-mode data channel must apply backpressure');
assert.match(out,/function csRemoteVisual\(/,'guard renderer must interpolate remote network snapshots');
assert.match(out,/\(now-p\.at\)\/220/,'guard interpolation must bridge the legacy 220 ms network cadence');
const remoteDraw=out.match(/function csDrawRemote\(\)\{[\s\S]*?\n\}/)?.[0]||'';
assert.match(remoteDraw,/const p=csRemoteVisual\(r\)/,'guard renderer must sample the interpolated remote pose');
assert.doesNotMatch(remoteDraw,/actor=\{x:r\.x\|\|0,y:r\.y\|\|0/,'guard renderer must not draw raw remote packet coordinates');
assert.match(out,/const csSharedRemotePose=new Map\(\)/,'shared rooms must keep independent interpolation state per remote peer');
assert.match(out,/stateSeq:\+\+csSharedStateSeq/,'shared room state packets must carry monotonic sequence numbers');
assert.match(out,/seq>Number\(prev\.stateSeq\|\|0\)/,'shared rooms must reject stale sequenced state packets');
assert.match(out,/csCoop\.dc\.bufferedAmount\|\|0\)<=65536/,'shared 2-4 player sender must apply data-channel backpressure');
const sharedDraw=out.match(/csDrawRemote=function\(\)\{if\(!shared\(\)\)[\s\S]*?csSharedRemotePose\.delete\(id\)\}\;/)?.[0]||'';
assert.match(sharedDraw,/Object\.values\(csCoop\.remotes\|\|\{\}\)/,'shared renderer must iterate all remote players');
assert.match(sharedDraw,/actor=\{x:p\.x,y:p\.y/,'shared renderer must draw interpolated per-peer positions');
assert.doesNotMatch(sharedDraw,/actor=\{x:r\.x\|\|0,y:r\.y\|\|0/,'shared renderer must not draw raw packet coordinates');

assert.doesNotMatch(out,/sesión social vencida/i,'integrated artifact must not expose expired-social-session UX');
assert.match(out,/window\.nsLobbyRtcStop=function/,'lobby RTC must expose deterministic teardown');
assert.match(out,/net\.peers\.clear\(\);net\.roster\.clear\(\);net\.remotes\.clear\(\)/,'RTC teardown must release peer and interpolation state');
assert.match(out,/state\.active=false;window\.nsLobbyRtcStop\?\.\(\)/,'leaving lobby must invoke RTC teardown');
console.log('4.8.7 source integration OK');

assert.doesNotMatch(out,/html\+=\\\\`/,'integrated inline JS must not contain escaped template delimiters');
assert.doesNotMatch(out,/nsEnterLobbySafe/,'timeout watchdog must not replace deterministic lobby initialization');
assert.match(out,/window\.nsLobby\.enter=enter/,'integrated artifact must export lobby enter');

assert.match(out,/natural-language-study-orders|const csStudyIntent=/,'artifact must accept natural-language study intent');
for(const verb of ['pedime','solicito','haceme','quiero','ordena','necesito'])assert.match(out,new RegExp(verb),'natural study vocabulary missing '+verb);
assert.match(out,/for\(const h of chosen\.sort/,'one natural sentence must order multiple recognized studies in spoken sequence');
assert.match(out,/seen\.has\(h\.st\.id\)/,'multi-study natural orders must deduplicate canonical studies');

assert.match(out,/findStudy=function\(text\)\{if\(negated\(language\(text\)\)\|\|question\(text\)\)return null;const native=match\(C\?\.studies,text\)/,'late language overlay must preserve native study precedence');
assert.match(out,/const global=match\(csStudyCatalog\(\),text\)/,'late language overlay must resolve universal studies');
assert.doesNotMatch(out,/findStudy=function\(text\)\{return negated\(language\(text\)\)\|\|question\(text\)\?null:match\(C\?\.studies,text\)/,'late overlay must not restore case-only study resolution');
assert.match(out,/sentFinals:new Set\(\)/,'speech recognizer tracks finalized result indexes');
assert.match(out,/csVoice\.sentFinals\.has\(i\)/,'speech recognizer must not resend finalized results');
assert.match(out,/csVoice\.sentFinals\.clear\(\)/,'speech recognizer resets finalized indexes on new recognition session');

assert.match(out,/faltan '\+Math\.max\(1,Math\.ceil\(\(o\.readyAt-performance\.now\(\)\)\/60000\)\)\+' h de juego'/,'pending studies must display real-time remaining game-hours');

assert.match(out,/id="atria-chat-bottom-anchor"/,'ward transcript positioning override must ship in the artifact');
assert.match(out,/body:not\(\.keyboardOpen\) #chatDock:not\(\.nsLobbyChat\) \.chatRecent\{position:absolute!important;top:auto!important;bottom:calc/,'ward transcript must anchor to composer instead of expanded dock top');
assert.match(out,/body:not\(\.keyboardOpen\) #chatDock\.historyExpanded:not\(\.nsLobbyChat\) \.chatRecent\{top:auto!important/,'expanded history must stay bottom-anchored');
assert.match(out,/function csMergeSpeech\(previous,incoming\)/,'speech must reconcile cumulative finalized fragments');
assert.match(out,/csVoiceQueue\(final\)/,'final WebSpeech fragments must be buffered rather than sent individually');
assert.match(out,/r\.onend=\(\)=>\{csVoiceFlush\(\)/,'pending final speech must flush when recognition stops');
const speechStart=out.indexOf('function csMergeSpeech(previous,incoming){'),speechEnd=out.indexOf('function csEnsureRecognition(){',speechStart);
assert.ok(speechStart>=0&&speechEnd>speechStart,'recognizer reconciliation helpers must be embedded');
const sent=[];const mock={csVoice:{pendingText:'',flushTimer:null},csCoop:{radioHeld:false},clearTimeout(){},setTimeout(fn){return fn},sendMessage(value){sent.push(value)}};vm.runInNewContext(out.slice(speechStart,speechEnd),mock);
for(const fragment of ['Hola','Hola qué','Hola qué te','Hola qué te pasó'])mock.csVoiceQueue(fragment);
mock.csVoiceFlush();assert.deepEqual(sent,['Hola qué te pasó'],'progressive Android speech must send exactly one complete utterance');
mock.csVoiceQueue('Pedime hemograma');mock.csVoiceQueue('hemograma y lipasa');mock.csVoiceFlush();assert.deepEqual(sent,['Hola qué te pasó','Pedime hemograma y lipasa'],'overlapping speech segments must not repeat words');
mock.csVoiceQueue('Hola hola');mock.csVoiceFlush();assert.equal(sent.at(-1),'Hola hola','literal spoken repetitions in a single final must be retained');
mock.csVoiceFlush();assert.equal(sent.length,3,'flushing empty buffer must never resend speech');
console.log('4.8.7 Android transcript anchoring and speech reconciliation OK');
