const replaceOnce=(s,from,to,label)=>{const i=s.indexOf(from);if(i<0)throw new Error('integration anchor missing: '+label);if(s.indexOf(from,i+from.length)>=0)throw new Error('integration anchor ambiguous: '+label);return s.slice(0,i)+to+s.slice(i+from.length)};
export function apply487(html){
 let s=html;
 // 4.8.7 replaces the legacy external study-repair pollers with source-level study resolution.
 s=replaceOnce(s,'<script src="/task8.js?v=482"></script>','<!-- legacy study poller 8 retired in 4.8.7 -->','retire-task8-study-poller');
 s=replaceOnce(s,'<script src="/task12.js?v=485"></script>','<!-- legacy study poller 12 retired in 4.8.7 -->','retire-task12-study-poller');
 // Prevent the legacy HUD/map from painting before the branded splash exists.
 const bootStyle=`<style id="atria-boot-paint-guard">html:not(.atriaBootReady) body>*{visibility:hidden!important}html:not(.atriaBootReady) body{background:#07121d!important}</style>`;
 s=replaceOnce(s,'</head>',bootStyle+'</head>','first-paint-guard');
 s=replaceOnce(s,`showSplash();renderSelector();brandHud();`,`showSplash();document.documentElement.classList.add('atriaBootReady');renderSelector();brandHud();`,'splash-first-paint-release');
 s=replaceOnce(s,` function showSplash(){const m=document.createElement('section');m.id='nsSplash';m.className='show';m.setAttribute('aria-label','Bienvenido a ATRIA');m.innerHTML='<div class="nsSplashInner">'+logo()+'<p class="nsEyebrow">GUARDIAS QUE ENSEÑAN</p>'+heroHTML()+'<h1>La noche empieza acá.</h1><p>Un hospital vivo. Decisiones clínicas. Tu próximo desafío.</p><button id="nsEnter" class="nsPrimary">'+(csProfile?'Continuar como '+csEscape(csProfile.name):'Crear mi personaje')+' →</button><small>Aprendiz · Solitario · Cooperativo · Competitivo</small></div>';document.body.appendChild(m);m.querySelector('button').onclick=()=>{splashOpen=false;m.classList.remove('show');if(!csProfile)csOpenProfile(true);else if(window.nsLobby?.enter)window.nsLobby.enter();else renderSelector();csHospitalAudio.unlock();};}`,` function showSplash(){const m=document.createElement('section');m.id='nsSplash';m.className='show';m.setAttribute('aria-label','Bienvenido a ATRIA');m.innerHTML='<div class="nsSplashInner">'+logo()+'<p class="nsEyebrow">GUARDIAS QUE ENSEÑAN</p>'+heroHTML()+'<h1>La noche empieza acá.</h1><p>Un hospital vivo. Decisiones clínicas. Tu próximo desafío.</p><button id="nsEnter" class="nsPrimary">'+(csProfile?'Continuar como '+csEscape(csProfile.name):'Crear mi personaje')+' →</button><small>Aprendiz · Solitario · Cooperativo · Competitivo</small></div>';document.body.appendChild(m);m.querySelector('button').onclick=()=>{splashOpen=false;m.classList.remove('show');if(!csProfile)csOpenProfile(true);else if(window.nsLobby?.enter)window.nsLobby.enter();else renderSelector();csHospitalAudio.unlock();};}`,'preserve-direct-splash-lobby-handoff');
 const oldFind=`function findStudy(text){const n=norm(text);let best=null,score=0;for(const s of C.studies)for(const a of [s.label,...s.aliases]){const na=norm(a);if(n.includes(na)&&na.length>score){best=s;score=na.length}}return best}`;
 const newFind=`function findStudy(text){const n=norm(text);let best=null,score=0,native=false;const nativeIds=new Set((C.studies||[]).map(x=>x.id)),pool=[...(C.studies||[])];for(const c of CASES||[])for(const x of c.studies||[])if(!pool.some(y=>y.id===x.id))pool.push(x);for(const st of pool)for(const a of [st.label,...(st.aliases||[])]){const na=norm(a);if(na&&n.includes(na)&&na.length>score){best=st;score=na.length;native=nativeIds.has(st.id)}}return best&&!native?{...best,result:'Sin alteraciones significativas para esta patología.',universalFallback:true}:best}`;
 s=replaceOnce(s,oldFind,newFind,'universal-study-resolution');
 const unknownStudy=`const i=findIntervention(raw.replace(/^orden\\s+/i,''));if(i){orderIntervention(i);return}nurseSay('No pude traducir esa orden. Probá /estudio <nombre> o /orden <conducta>.')`;
 const universalOrder=`const i=findIntervention(raw.replace(/^orden\\s+/i,''));if(i){orderIntervention(i);return}if(/^estudio\\s+/i.test(raw)){const label=raw.replace(/^estudio\\s+/i,'').trim();if(label){orderStudy({id:'universal_'+norm(label).replace(/\\s+/g,'_').slice(0,48),label,aliases:[label],type:'lab',delay:2,result:'Sin alteraciones significativas para esta patología.',universalFallback:true});return}}nurseSay('Indicame el nombre del estudio o la conducta.')`;
 s=replaceOnce(s,unknownStudy,universalOrder,'free-universal-study-order');
 let direct=0;s=s.replace(/s\.delay\*1000/g,()=>{direct++;return 'Math.max(1,Number(s.gameHours??s.delayHours??s.delay??1))*60000'});if(direct!==1)throw new Error('direct study timing anchor expected 1, got '+direct);
 let lab=0;s=s.replace(/t\.study\.delay\*1000/g,()=>{lab++;return 'Math.max(1,Number(t.study.gameHours??t.study.delayHours??t.study.delay??1))*60000'});if(lab!==1)throw new Error('lab study timing anchor expected 1, got '+lab);
 const socialExport=`window.nsSocial={state,render,health,connect,register,search,refresh,addFriend:id=>friendAction('friends',id),acceptFriend:id=>friendAction('friends/accept',id),declineFriend:id=>friendAction('friends/decline',id),createRoom,inviteToRoom,joinRoom,declineRoom,removeInvite,cancelRoom,leave,role:()=>room?.role||null,room:()=>room};`;
 const socialExportSafe=`window.nsSocial={state,render,health,connect,register,ensureSession:async()=>{const data=await acquireSession();await refresh();return data.user},search,refresh,addFriend:id=>friendAction('friends',id),acceptFriend:id=>friendAction('friends/accept',id),declineFriend:id=>friendAction('friends/decline',id),createRoom,inviteToRoom,joinRoom,declineRoom,removeInvite,cancelRoom,leave,role:()=>room?.role||null,room:()=>room};`;
 s=replaceOnce(s,socialExport,socialExportSafe,'single-social-session-owner');
 // Social bootstrap is idempotent: acquire/resume the profile instead of racing a second registration.
 const oldEnsureSocial=`async function ensureSocial(){try{await nsSocial?.health?.();let s=social();if(!s.available){state.status='Lobby local · el servidor social no está conectado.';return false}if(!s.user){const raw=(csProfile?.name||'medico').normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'').slice(0,22)||'medico';const alias=raw.length>=3?raw:(raw+'_med').slice(0,22);try{await nsSocial.register(alias)}catch(err){state.status='Reconectando tu perfil · '+(err?.message||'sin conexión');return false}s=social()}await nsSocial.refresh();return true}catch(err){state.status='Lobby local · '+(err?.message||'sin conexión');return false}}`;
 const newEnsureSocial=`async function ensureSocial(){try{await nsSocial?.health?.();let s=social();if(!s.available){state.status='Lobby local · el servidor social no está conectado.';return false}if(!s.user){await nsSocial.ensureSession();s=social()}if(!s.user){state.status='Lobby local · perfil social no disponible.';return false}await nsSocial.refresh();return true}catch(err){console.warn('ATRIA social bootstrap',err);state.status='Lobby local · conexión social temporalmente no disponible.';return false}}`;
 s=replaceOnce(s,oldEnsureSocial,newEnsureSocial,'idempotent-social-bootstrap');
 // The legacy RTC lobby installed a second permanent RAF/network scheduler. Keep one owner: nsLobby tick.
 const rtcStatsAnchor=`window.nsLobbyRtcStats=function(){var out=[];net.peers.forEach(function(r,id){out.push({id:id,peerId:r.peerId,open:!!r.open,connecting:!!r.connecting,state:r.pc&&r.pc.connectionState||'none',channel:r.dc&&r.dc.readyState||'none'})});return out};`;
 const rtcStatsSafe=rtcStatsAnchor+`\n  window.nsLobbyRtcStop=function(){net.peers.forEach(function(r){try{if(r.dc)r.dc.close()}catch(_){}try{if(r.pc)r.pc.close()}catch(_){}});net.peers.clear();net.roster.clear();net.remotes.clear();net.discovering=false;net.lastDiscovery=0;net.lastRtcSend=0;net.lastFrame=0};`;
 s=replaceOnce(s,rtcStatsAnchor,rtcStatsSafe,'rtc-lobby-cleanup');
 const deactivateAnchor=`function deactivate({notify=true}={}){state.epoch++;if(!state.active)return;state.active=false;`;
 s=replaceOnce(s,deactivateAnchor,`function deactivate({notify=true}={}){state.epoch++;if(!state.active)return;state.active=false;window.nsLobbyRtcStop?.();`,'rtc-cleanup-on-lobby-leave');
 const rtcStart=`setTimeout(discovery,250);requestAnimationFrame(animate);`;
 s=replaceOnce(s,rtcStart,`// RTC discovery is driven conservatively from the primary lobby scheduler; no second permanent RAF.\n  window.nsLobbyRtcPulse=function(ts){if(!window.nsLobby?.active)return;ts=Number(ts)||performance.now();if(ts-net.lastRtcSend>=220){net.lastRtcSend=ts;var p=localState();if(p)sendRtc(p)}if(ts-net.lastDiscovery>=2500){net.lastDiscovery=ts;discovery()}};`,'single-lobby-scheduler');
 const socialPulse=`if((state._lastSocial||0)+1000<t){state._lastSocial=t;nsSocial?.refresh?.().then(()=>{renderHud();if(document.getElementById('nsLobbyGuard')?.classList.contains('show')&&social().room)openWaitingRoom()}).catch(()=>{})}`;
 s=replaceOnce(s,socialPulse,`if((state._lastSocial||0)+2500<t){state._lastSocial=t;nsSocial?.refresh?.().then(()=>{renderHud();if(document.getElementById('nsLobbyGuard')?.classList.contains('show')&&social().room)openWaitingRoom()}).catch(()=>{})}window.nsLobbyRtcPulse?.(t)`,'bounded-social-rtc-pulse');
 const activationText='Activa una vez tu perfil social. El alias parte del nombre de tu personaje.';
 const activationAt=s.indexOf(activationText);if(activationAt<0)throw new Error('integration anchor missing: people-auto-presence');
 const activationStart=s.lastIndexOf("else if(!s.user){",activationAt),activationEnd=s.indexOf("}\n else{",activationAt);if(activationStart<0||activationEnd<0)throw new Error('integration anchor malformed: people-auto-presence');
 s=s.slice(0,activationStart)+"else if(!s.user){html+='<div class=\"nsPeopleOffline\">Conectando tu perfil automáticamente…</div>';nsSocial?.ensureSession?.().then(()=>{if(document.getElementById('nsPeopleModal')?.classList.contains('show'))openPeople()}).catch(()=>{})}"+s.slice(activationEnd+1);
 // Smooth the legacy 220 ms guard-network snapshots at render cadence instead of drawing raw packet positions.
 const rawRemote=`function csDrawRemote(){
 const r=csCoop.remote;if(!csCoop.connected||!r||!C||r.caseId!==C.id)return;
 const key=r.coat?'coat':(r.color||'navy'),im=csVariantImgs[key]||csVariantImgs.navy;if(!im?.complete)return;
 const actor={x:r.x||0,y:r.y||0,dir:r.dir||'S',moving:!!r.moving,walkPhase:r.walkPhase||0};drawSprite(im,actor,60);csDrawNameplate(actor,r.name||'Compañero',r.level||1,true)
}`;
 const smoothRemote=`let csRemotePose=null;
function csRemoteVisual(r,now=performance.now()){if(!csRemotePose){csRemotePose={x:Number(r.x)||0,y:Number(r.y)||0,fromX:Number(r.x)||0,fromY:Number(r.y)||0,toX:Number(r.x)||0,toY:Number(r.y)||0,at:now}}if(csRemotePose.toX!==(Number(r.x)||0)||csRemotePose.toY!==(Number(r.y)||0)){const p=csRemoteVisualSample(now);csRemotePose={x:p.x,y:p.y,fromX:p.x,fromY:p.y,toX:Number(r.x)||0,toY:Number(r.y)||0,at:now}}return csRemoteVisualSample(now)}
function csRemoteVisualSample(now=performance.now()){const p=csRemotePose;if(!p)return{x:0,y:0};const t=Math.max(0,Math.min(1,(now-p.at)/220)),e=t*t*(3-2*t);return{x:p.fromX+(p.toX-p.fromX)*e,y:p.fromY+(p.toY-p.fromY)*e}}
function csDrawRemote(){
 const r=csCoop.remote;if(!csCoop.connected||!r||!C||r.caseId!==C.id){csRemotePose=null;return}
 const key=r.coat?'coat':(r.color||'navy'),im=csVariantImgs[key]||csVariantImgs.navy;if(!im?.complete)return;
 const p=csRemoteVisual(r),actor={x:p.x,y:p.y,dir:r.dir||'S',moving:!!r.moving,walkPhase:r.walkPhase||0};drawSprite(im,actor,60);csDrawNameplate(actor,r.name||'Compañero',r.level||1,true)
}`;
 s=replaceOnce(s,rawRemote,smoothRemote,'guard-remote-interpolation');
 const oldPeer=`function csSendPeerState(){\n if(!csCoop.dc||csCoop.dc.readyState!=='open'||!csProfile)return;`;
 const newPeer=`function csSendPeerState(){\n if(!csCoop.dc||csCoop.dc.readyState!=='open'||!csProfile)return;\n if((csCoop.dc.bufferedAmount||0)>65536)return;`;
 s=replaceOnce(s,oldPeer,newPeer,'peer-backpressure');
 const disabledVoice=` // Player radio needs a voice transport; this release provides clinical data and text only.\n const refreshVoice=csRefreshVoiceButtons;\n csRefreshVoiceButtons=function(){const r=refreshVoice.apply(this,arguments),b=document.getElementById('radioPttBtn');if(b){b.disabled=true;b.hidden=true;b.title='La sala comparte texto y acciones. Radio de voz pendiente.';}return r;};\n csRefreshVoiceButtons();`;
 s=replaceOnce(s,disabledVoice,` // Existing WebRTC audio transport is enabled; task13 handles mic permission priming.\n csRefreshVoiceButtons();`,'social-voice-enable');
 return s;
}
