import assert from 'node:assert/strict';
import {csVoiceStageRevisions,csVoiceCommitRevisions} from './revision-buffer.js';
const final=(text)=>({0:{transcript:text},isFinal:true});
const interim=(text)=>({0:{transcript:text},isFinal:false});
const pending=new Map(),delivered=new Set();
let r=csVoiceStageRevisions(pending,delivered,{resultIndex:0,results:[interim('Qué medicación toma')]});
assert.equal(r.text,'','interim is never sent to patient');
r=csVoiceStageRevisions(pending,delivered,{resultIndex:0,results:[interim('Qué medicación habitual')]});
assert.equal(r.text,'','revision of interim overwrites instead of appending');
r=csVoiceStageRevisions(pending,delivered,{resultIndex:0,results:[final('Qué medicación toma')]});
assert.equal(r.text,'Qué medicación toma');
r=csVoiceStageRevisions(pending,delivered,{resultIndex:0,results:[final('Qué medicación habitual toma')]});
assert.equal(r.text,'Qué medicación habitual toma','same-index final correction replaces prior result');
assert.equal(csVoiceCommitRevisions(pending,delivered),'Qué medicación habitual toma');
assert.equal(pending.size,0);
r=csVoiceStageRevisions(pending,delivered,{resultIndex:0,results:[final('Qué medicación habitual toma')]});
assert.equal(r.text,'','old finalized index must never be resent');
r=csVoiceStageRevisions(pending,delivered,{resultIndex:1,results:[final('Qué medicación habitual toma'),final('¿Desde cuándo?')]});
assert.equal(r.text,'¿Desde cuándo?','next result index can carry genuine new speech');
assert.equal(csVoiceCommitRevisions(pending,delivered),'¿Desde cuándo?');
const extra=new Map(),sent=new Set();
r=csVoiceStageRevisions(extra,sent,{resultIndex:0,results:[final('Algún hábito'),interim('fuma tabaco')]});
assert.equal(r.text,'Algún hábito');
r=csVoiceStageRevisions(extra,sent,{resultIndex:1,results:[final('Algún hábito'),final('hábito de fumar tabaco')]});
assert.equal(r.text,'Algún hábito de fumar tabaco','different indexes with overlapping text join without duplicate prefix');
assert.equal(csVoiceCommitRevisions(extra,sent),'Algún hábito de fumar tabaco');
const unsent=new Map(),unused=new Set();
csVoiceStageRevisions(unsent,unused,{resultIndex:0,results:[final('¿Tiene antecedentes de alergia?')]});
csVoiceStageRevisions(unsent,unused,{resultIndex:0,results:[interim('¿Tiene alergia a algún medicamento?')]});
assert.equal(unsent.size,0,'new interim version revokes previously finalized uncommitted hypothesis');
csVoiceStageRevisions(unsent,unused,{resultIndex:0,results:[final('¿Tiene alergia a algún medicamento?')]});
assert.equal(csVoiceCommitRevisions(unsent,unused),'¿Tiene alergia a algún medicamento?');
console.log('Web Speech interim/final replacement by result index OK');
